services:
  aipan:
    image: unilei/aipan-netdisk-search:latest
    container_name: aipan-netdisk-search-app
    restart: always
    ports:
      - "3003:3000"
    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Manticore-search_A.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://aipan.hugocheng.top:1029/
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Manticore-search_A.png