---
version: "3"
services:
  alist:
    image: xhofe/alist-aria2:latest
    container_name: alist
    hostname: alist
    volumes:
      - /mnt/user/appdata/alist:/opt/alist/data
      - /mnt/user/:/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    network_mode: host
    restart: unless-stopped
    labels:
      icon: http://IP:PORT/i/user_01/alist.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://alist.hugocheng.top:1029
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius//Alist_A.png
