services:
  allinone:
    image: youshandefeiyang/allinone:latest
    container_name: allinone
    privileged: true
    restart: always
    ports:
      - "35455:35455"
    network_mode: bridge
    command: -tv=true -aesKey=lr80thv1vwwike3h0nie6xni7s9b8quv -userid=7083529425 -token=a7c985a825049992005ccc2f3c31b1a8d32b013bcc515f374d80363d83cd90cb9f7915b4692966d55de1633c57e0185aa8bfd55afcfa04196d14bf71db00ca7b3660b1885874b8
    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Iptv_G.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://iptv.hugocheng.top:1029/tv.m3u?url=https://iptv.hugocheng.top:1029
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Iptv_G.png
