version: "2.1"
services:
  baidunetdisk:
    image: johngong/baidunetdisk:latest
    container_name: baidunetdisk
    environment:
      - TZ=Etc/UTC
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/user/media/baidunetdisk:/download/
      - /mnt/user/appdata/baidunetdisk/config:/config
    ports:
      - 8092:5800
    restart: always
    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Calibre_A.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://baidu.hugocheng.top:1029
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius//Baidudrive_A.png
    