version: "2.1"
services:
  calibre:
    image: johngong/calibre-web
    container_name: calibre
    environment:
      - TZ=Etc/UTC
      - WEBUI_PORT=8999
    volumes:
      - /mnt/user/appdata/calibre:/config
      - /mnt/user/media/ebook:/ebook
    ports:
      - 8083:8083
    restart: always
    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Calibre_A.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://calibre.hugocheng.top:1029
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Calibre_A.png