version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    volumes:
      - /mnt/user/appdata/chinesesubfinder/config:/config
      - /mnt/user/appdata/chinesesubfinder/cache:/app/cache
      - /mnt/usr/media/link/电影:/media/movie
      - /mnt/usr/media/link/电视剧:/media/tv
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 19035:19035
    restart: unless-stopped
    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius//Chinesesubfinder_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://chinesesubfinder.hugocheng.top:1029
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius//Chinesesubfinder_A.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑