version: "2.1"
services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    container_name: cookiecloud
    environment:
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/cookiecloud/config:/config
    ports:
      - 8088:8088
    restart: always
    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Cookiecloud_A.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://cookiecloud.hugocheng.top:1029
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Cookiecloud_A.png