version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    volumes:
      - /mnt/user/appdata/duplicati:/config
      - /mnt/user/duplicati:/backups
      - /mnt/user:/source
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - SETTINGS_ENCRYPTION_KEY=ThiErry_098
      - DUPLICATI__WEBSERVICE_PASSWORD=ThiErry_098
    network_mode: host
    restart: always
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://duplicati.hugocheng.top:1029/
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Duplicati_A.png