version: "3.8"

services:
  php-runtime:
    image: livecodesvip/php-runtime:latest
    container_name: php-runtime
    restart: always
    ports:
      - "5080:80"
      - "5090:8080"
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: ThiErry_098
    volumes:
      - php-runtime_repo:/var/www/repo
      - /mnt/user/appdata/phpiptv:/config
    labels:
      icon: https://github.com/xushier/HD-Icons/blob/7c0308fd086d5465a8948844e55de5d7bc49c051/border-radius/Iptv_D.png
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://php.hugocheng.top
      net.unraid.docker.icon: https://github.com/xushier/HD-Icons/blob/7c0308fd086d5465a8948844e55de5d7bc49c051/border-radius/Iptv_D.png
volumes:
  php-runtime_repo: