version: '3.3'

services:

    moviepilot:
        stdin_open: true
        tty: true
        container_name: moviepilot-v2
        hostname: moviepilot-v2
        networks:
            - moviepilot
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
        volumes:
            - '/mnt/user/media:/media'
            - '/mnt/user/appdata/moviepilot2:/config'
            - '/mnt/user/appdata/moviepilot2/core:/moviepilot/.cache/ms-playwright'
            - '/mnt/user/appdata/qbittorrent/config/qBittorrent/BT_backup:/qb'
            - '/mnt/user/appdata/transmission/torrents:/tr'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        environment:
            - 'NGINX_PORT=3000'
            - 'PORT=3001'
            - 'PUID=0'
            - 'PGID=0'
            - 'UMASK=000'
            - 'TZ=Asia/Shanghai'
            - 'AUTH_SITE=iyuu,hdfans'
            - 'IYUU_SIGN=IYUU141Tb4ff3f7f3f4f9416f351e7002983f8735a08f08a'
            - 'HDFANS_UID=48206'
            - 'HDFANS_PASSKEY=811f4b82afd04bd2ed36628c00c4257f'            
            - 'SUPERUSER=admin'
            - 'PROXY_HOST=http://192.168.50.234:1080'

        restart: always
        image: jxxghp/moviepilot-v2:latest

        labels:
            icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Moviepilot_A.png
            # 适用于CasaOS导入时自动写上图标地址
            # 注意：在导入CasaOS时，记得补全本机端口号
            # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
            ########################################
            net.unraid.docker.managed: dockerman
            net.unraid.docker.webui: https://moviepilot.hugocheng.top:1029
            # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
            net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Moviepilot_A.png
            # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
            # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑

networks:
  moviepilot:
    name: moviepilot