services:
  myServers:
    image: myservers/my_servers:latest
    network_mode: host
    container_name: myservers
    volumes:
      - /proc:/proc
      - /var/run:/var/run
      - /mnt/user/appdata/myservers/data:/app/data
      - /mnt/user/appdata/myservers/config:/app/config
    command: /app/app -k e8edf0cd4c5
    restart: always
    labels:
      icon: httphttps://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Jumpserver_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://myservers.hugocheng.top:1029
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Jumpserver_A.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑