version: "3.3"
services:
  homepage:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    ports:
      - 3334:3002
    volumes:
      - /mnt/user/appdata/sun-panel/config:/app/conf # Make sure your local config directory exists
      - /mnt/user/appdata/sun-panel/config/uploads:/app/uploads
      - /mnt/user/appdata/sun-panel/config/database:/app/database 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: always

    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Sunpanel_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://sunpanel.hugocheng.top:1029
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Sunpanel_A.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑