version: "3"
services:
  zbook:
    image: bigmouse0001/zbook:latest
    volumes:
      - /mnt/user/appdata/zbook/config:/config
      - /mnt/user/appdata/zbook/index:/index
    environment:
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    restart: always
    network_mode: bridge
    hostname: zbook
    container_name: zbook
    ports:
      - 9000:80
    labels:
      icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Bookstack_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: https://zbook.hugocheng.top:1029
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: https://raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Bookstack_A.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑